apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo Servicenow Create
on:
  workflow_dispatch:
    inputs:
      CR_Title:
        type: string
        default: Test CR
        required: true
jobs:
  create-with-baseAuth:
    steps:
      - name: Servicenow Create Normal Ticket
        uses: calculi-corp/template-servicenow-actions/servicenow
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: create
          cr-type: Normal
          short-description: ${{ inputs.CR_Title }}
