apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo Servicenow Create
on:
  workflow_dispatch:
jobs:
  create-with-baseAuth:
    steps:
      - name: Servicenow Create Normal Ticket
        uses: calculi-corp/template-servicenow-actions/servicenow
        with:
          url: ${{ vars.SERVICENOW_URL2 }}
          username: ${{ secrets.SERVICENOW_USERNAME2 }}
          password: ${{ secrets.SERVICENOW_PASSWORD2 }}
          action-type: create
          cr-type: Normal
          short-description: "Service Now Actions Testing - Normal CR"