apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo ServiceNow Update
on:
  workflow_dispatch:
jobs:
  update-with-baseAuth:
    steps:
      - name: Trigger Servicenow Update Mode
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: 07d07eabdb9ed21037ff892d13961990
          description: "Updating Description from CBP Workflow"
          state: "Assess"
          priority: "3 - Moderate"
          risk: "Low"
          additional-parameters : '{"risk_impact_analysis":"No known risks","implementation_plan": "Describe the implementation plan here"}'
        
          
  get-with-baseAuth:
    needs:
      - update-with-baseAuth
    steps:
      - name: Trigger Servicenow Get Mode
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: GET
          cr-number: CHG0047023