apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Demo ServiceNow Update
on:
  workflow_dispatch:
jobs:
  update-with-baseAuth:
    steps:
      - name: Trigger Servicenow Update Mode
        uses: calculi-corp/template-servicenow-actions/servicenow
        with:
          url: ${{ vars.SERVICENOW_URL2 }}
          username: ${{ secrets.SERVICENOW_USERNAME2 }}
          password: ${{ secrets.SERVICENOW_PASSWORD2 }}
          action-type: update
          sys-id: 0adcd7effb969610cbc0fbef4eefdca4
          description: "Updating Description from CBP Workflow"
          state: "Assess"
          assignment-group: "Change Management"
          priority: "3 - Moderate"
          risk: "Low"
          additional-parameters : '{"risk_impact_analysis":"No known risks","implementation_plan": "Describe the implementation plan here"}'
        
          
  get-with-baseAuth:
    needs:
      - update-with-baseAuth
    steps:
      - name: Trigger Servicenow Get Mode
        uses: calculi-corp/template-servicenow-actions/servicenow
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: GET
          cr-number: CHG0031542