apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Dispatch multiple workflows
on:
  workflow_dispatch:
jobs:
  dispatch-workflows:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: Dispatch workflows
        uses: cloudbees-io/workflows-dispatch@main
        with:
          workflows-dispatch-file: dispatch_requests.json
          token: ${{ secrets.MY_PAT }}
