apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow
on:
  workflow_dispatch:
jobs:
  call-reusable-workflow:
    uses: B-Aruna/MyFirstProject/.cloudbees/workflows/reusable.yaml
