apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow

on:
  push:
    branches:
      - '**'

jobs:
  call-reusable-workflow:
    uses: B-Aruna/MyFirstProject/blob/main/.cloudbees/workflows/reusable.yaml
