apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - 'main'

jobs:
  hello:
    steps:
      - name: say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: echo "Hello World!"
