apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow2
on:
  workflow_dispatch: {}
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Welcome User
        shell: sh
        run: |
          echo "Welcome "${{vars.username}}!
          echo "Your password is "${{secrets.password}}
