apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow2
on:
  workflow_dispatch: {}
jobs:
  welcome:
    environment: Prod
    steps:
      - uses: docker://golang:1.20
        name: Welcome User
        shell: sh
        run: |
          echo "Welcome "${{vars.username}}!
          echo "Your password is "${{secrets.password}}
    outputs:
      welcomeuser_firstname: ${{vars.username}}
      welcomeuser_lastname: Balasubramanian
  goodbye:
    steps:
      - uses: docker://golang:1.20
        name: Say Goodbye
        kind: deploy
        run: echo "Goodbye "${{needs.welcome.outputs.welcomeuser_firstname}}
          ${{needs.welcome.outputs.welcomeuser_lastname}} !!
    needs: welcome
