apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Pull Request Test
on:
  pull_request:
    branches:
      - 'main'
jobs:
  welcome:
    steps:
      - uses: docker://golang:1.20
        name: Welcome User
        shell: sh
        run: |
          echo "Welcome "