apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Run Github Action
on:
  workflow_dispatch:
jobs:
  run-gha-workflow:
    steps:
      - name: Run GHA workflow
        uses: cloudbees-io/ghactions-run-workflow@v2
        with:
          url: ${{ vars.GITHUB_URL }}
          token: ${{ secrets.GHA_TOKEN }}
          org-name: B-Aruna
          repo-name: MyFirstProject
          branch-name: main
          workflow-name: main
          