apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Run Github Action
on:
  workflow_dispatch:
jobs:
  run-gha-workflow:
    steps:
      - name: Run GHA workflow
        uses: cloudbees-io/ghactions-run-workflow@v2
        with:
          url: ${{ vars.GITHUB_URL }}
          token: ${{ secrets.GHA_TOKEN }}
          org-name: my_org
          repo-name: my_repo
          branch-name: main
          workflow-name: BUILD_PARAM
          test-type: Junit
          test-result-location: junit-service*
          parameters: '{"ENV_NAME":"TEST"}'