apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: update-sn-cr-status
on:
  workflow_dispatch:
    inputs:
      sys_id:
        type: string
        required: true
jobs:
  update-cr-status:
    steps:
      - id: servicenow-update-assess
        name: Trigger Servicenow Update Assess state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Assess
          assignment-group: Change Management
      - id: servicenow-update-authorize
        name: Trigger Servicenow Update Authorize state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Authorize
      - id: servicenow-update-scheduled
        name: Trigger Servicenow Update Scheduled state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Scheduled
      - id: servicenow-update-scheduled
        name: Trigger Servicenow Update Scheduled state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Scheduled
      - id: servicenow-update-implement
        name: Trigger Servicenow Update Implement state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Implement
      - id: servicenow-update-review
        name: Trigger Servicenow Update Implement state
        uses: cloudbees-io/servicenow@v1
        with:
          url: ${{ vars.SERVICENOW_URL }}
          username: ${{ secrets.SERVICENOW_USERNAME }}
          password: ${{ secrets.SERVICENOW_PASSWORD }}
          action-type: update
          sys-id: ${{inputs.sys_id }}
          state: Review
      
